spring:
  profiles:
    active: dev
  application:
    name: djyuning-blog-website
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  # SESSION
  session:
    store-type: redis
  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123321

# Mybatis 配置
mybatis:
  type-aliases-package: me.djyuning.blog-website
  mapper-locations: classpath\:mapper/*.xml

# 分页配置
pager:
  num: 5 # 每次显示 5 页
  size: 4 # 每页显示 10 条数据
  param: "p" # 地址栏取参数
