# 服务器
server:
  port: 8081

# Spring
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_first?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
